version: "3.9"

services: 
  frontend:
    container_name: player_music_frontend
    build: 
      context: ../
      dockerfile: frontend.dockerfile
      labels: 
        - "com.example.description: player-music-frontend"
      args: 
        buildno: 1
    ports: 
      - "9090:80"
      
  backend:
    container_name: player_music_backend
    build: 
      context: ../
      dockerfile: backend.dockerfile
      labels: 
        - "com.example.description: player-music-backend"
      args: 
        buildno: 1
    ports: 
      - "5000:5000"
      

    